name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*" ]
  schedule:
    - cron: "0 4 * * 1,4"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Latest Tag
        if: github.event_name == 'schedule'
        id: determine-ref
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "ref=$latest_tag" >> $GITHUB_OUTPUT

      - name: Checkout Latest Tag
        if: github.event_name == 'schedule'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.determine-ref.outputs.ref }}
          fetch-depth: 0

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build And Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update DockerHub Readme
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
